name: Deploy to VPS
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Execute deploy commands
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            # Загружаем окружение (fnm + pnpm)
            source ~/.bashrc || true
            source ~/.zshrc || true

            cd ${{ secrets.VPS_PATH }} &&
            git pull origin main &&
            pnpm install --frozen-lockfile &&
            pnpm build &&
            pm2 restart front
          "
